import React, { useState, useEffect } from 'react';
import { api } from '../api';
import { Mail, Copy, ExternalLink, RefreshCw, Clock, Trash2 } from 'lucide-react';

export default function VirtualMailbox({ user, addToast }) {
  const [emails, setEmails] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedIds, setSelectedIds] = useState([]);

  const fetchEmails = async () => {
    try {
      setLoading(true);
      const res = await api.getEmails();
      setEmails(res);
    } catch (err) {
      addToast(err.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEmails();
  }, []);

  const copyLink = (link) => {
    navigator.clipboard.writeText(link);
    addToast('Invitation link copied to clipboard!');
  };

  const handleDeleteEmail = async (id) => {
    if (!window.confirm('Are you sure you want to delete this simulated email from the outbox?')) {
      return;
    }
    try {
      await api.deleteEmail(id);
      addToast('Simulated email deleted.');
      setSelectedIds(prev => prev.filter(x => x !== id));
      fetchEmails();
    } catch (err) {
      addToast(err.message, 'error');
    }
  };

  const handleBulkDelete = async () => {
    if (selectedIds.length === 0) return;
    if (!window.confirm(`Are you sure you want to delete the ${selectedIds.length} selected simulated emails? This action is permanent.`)) {
      return;
    }
    try {
      await api.bulkDeleteEmails(selectedIds);
      addToast(`${selectedIds.length} emails deleted successfully.`);
      setSelectedIds([]);
      fetchEmails();
    } catch (err) {
      addToast(err.message, 'error');
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', padding: '3rem' }}>
        <RefreshCw className="animate-spin" size={32} style={{ color: 'var(--color-primary)' }} />
      </div>
    );
  }

  return (
    <div className="animate-fade" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2>Virtual Outbox Simulation</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
            This simulator catches local emails generated by the system when you invite external candidates. Click links below to proceed as a candidate.
          </p>
        </div>
        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
          {emails.length > 0 && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', background: 'var(--color-card)', border: '1px solid var(--color-border)', padding: '0.5rem 0.75rem', borderRadius: 'var(--radius-sm)' }}>
              <input 
                type="checkbox" 
                checked={emails.length > 0 && emails.every(e => selectedIds.includes(e.id))}
                onChange={(e) => {
                  if (e.target.checked) {
                    setSelectedIds(emails.map(x => x.id));
                  } else {
                    setSelectedIds([]);
                  }
                }}
                style={{ cursor: 'pointer' }}
                id="select-all-emails"
              />
              <label htmlFor="select-all-emails" style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-secondary)', cursor: 'pointer', margin: 0 }}>Select All</label>
            </div>
          )}
          <button onClick={fetchEmails} className="btn btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <RefreshCw size={18} />
            <span>Refresh Mailbox</span>
          </button>
        </div>
      </div>

      {selectedIds.length > 0 && (
        <div className="card animate-fade" style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem 1rem', background: 'rgba(239, 68, 68, 0.05)', border: '1px solid rgba(239, 68, 68, 0.2)', borderRadius: 'var(--radius-md)' }}>
          <span style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--color-danger)' }}>
            {selectedIds.length} simulated emails selected
          </span>
          <button onClick={handleBulkDelete} className="btn btn-danger btn-sm" style={{ display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
            <Trash2 size={14} />
            <span>Delete Selected</span>
          </button>
        </div>
      )}

      {/* Outbox List */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        {emails.length === 0 ? (
          <div className="card" style={{ textAlign: 'center', padding: '4rem', color: 'var(--text-muted)' }}>
            <Mail size={48} style={{ margin: '0 auto 1rem auto', color: 'var(--color-border)' }} />
            <h4>No Emails Sent Yet</h4>
            <p style={{ fontSize: '0.85rem' }}>
              Create an invitation from the Dashboard using "Invite Candidate" to log outbound mails.
            </p>
          </div>
        ) : (
          emails.map(email => (
            <div key={email.id} className="card" style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '0.75rem',
              borderLeft: '4px solid var(--color-primary)',
              background: selectedIds.includes(email.id) ? 'rgba(74, 125, 135, 0.1)' : 'var(--color-card)'
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '1px solid var(--color-border)', paddingBottom: '0.5rem' }}>
                <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
                  <input 
                    type="checkbox" 
                    checked={selectedIds.includes(email.id)}
                    onChange={(e) => {
                      if (e.target.checked) {
                        setSelectedIds(prev => [...prev, email.id]);
                      } else {
                        setSelectedIds(prev => prev.filter(x => x !== email.id));
                      }
                    }}
                    style={{ cursor: 'pointer' }}
                  />
                  <div>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600 }}>RECIPIENT</div>
                    <div style={{ fontWeight: 700, color: 'var(--color-primary)' }}>{email.to_email}</div>
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                    <Clock size={12} />
                    <span>{new Date(email.sent_at).toLocaleString()}</span>
                  </div>
                  {user.role === 'admin' && (
                    <button 
                      onClick={() => handleDeleteEmail(email.id)} 
                      className="btn btn-danger btn-sm" 
                      style={{ padding: '0.25rem', background: 'none', border: 'none', color: 'var(--color-danger)', cursor: 'pointer', display: 'flex', alignItems: 'center' }}
                      title="Delete email"
                    >
                      <Trash2 size={16} />
                    </button>
                  )}
                </div>
              </div>

              <div>
                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600 }}>SUBJECT</div>
                <div style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{email.subject}</div>
              </div>

              <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', marginTop: '0.25rem' }}>
                <input 
                  type="text" 
                  readOnly 
                  value={email.link} 
                  style={{ background: 'var(--color-bg)', color: 'var(--text-secondary)', fontSize: '0.8rem', padding: '0.5rem' }} 
                />
                
                <button onClick={() => copyLink(email.link)} className="btn btn-accent btn-sm" style={{ display: 'flex', alignItems: 'center', padding: '0.5rem' }}>
                  <Copy size={16} />
                </button>

                <a 
                  href={email.link} 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="btn btn-secondary btn-sm" 
                  style={{ display: 'inline-flex', alignItems: 'center', gap: '0.25rem', padding: '0.5rem 0.75rem' }}
                >
                  <span>Launch Session</span>
                  <ExternalLink size={14} />
                </a>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
